import { Injectable } from '@nestjs/common';
import { BatterStats, PitcherStats, GameRecord } from '../entities';

@Injectable()
export class MockDataService {
  getBattersMockData(): BatterStats[] {
    return [
      {
        playerId: 'BAT001',
        playerNumber: '1',
        playerName: '陳晨威',
        PA: 150,
        AB: 120,
        H: 45,
        '2B': 8,
        '3B': 2,
        HR: 5,
        R: 28,
        RBI: 32,
        BB: 20,
        IBB: 2,
        HBP: 3,
        SO: 18,
        SH: 2,
        SF: 1,
        E: 0,
        SB: 5,
        CS: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'BAT002',
        playerNumber: '2',
        playerName: '林家翔',
        PA: 145,
        AB: 115,
        H: 42,
        '2B': 6,
        '3B': 1,
        HR: 4,
        R: 25,
        RBI: 28,
        BB: 22,
        IBB: 1,
        HBP: 2,
        SO: 20,
        SH: 3,
        SF: 2,
        E: 1,
        SB: 8,
        CS: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'BAT003',
        playerNumber: '3',
        playerName: '王柏融',
        PA: 155,
        AB: 128,
        H: 50,
        '2B': 10,
        '3B': 3,
        HR: 8,
        R: 35,
        RBI: 42,
        BB: 18,
        IBB: 3,
        HBP: 2,
        SO: 22,
        SH: 1,
        SF: 0,
        E: 0,
        SB: 3,
        CS: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'BAT004',
        playerNumber: '4',
        playerName: '江坤宇',
        PA: 148,
        AB: 118,
        H: 40,
        '2B': 7,
        '3B': 1,
        HR: 6,
        R: 26,
        RBI: 35,
        BB: 21,
        IBB: 2,
        HBP: 3,
        SO: 25,
        SH: 2,
        SF: 1,
        E: 1,
        SB: 4,
        CS: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'BAT005',
        playerNumber: '5',
        playerName: '高志綱',
        PA: 152,
        AB: 122,
        H: 44,
        '2B': 8,
        '3B': 2,
        HR: 7,
        R: 30,
        RBI: 38,
        BB: 20,
        IBB: 1,
        HBP: 2,
        SO: 19,
        SH: 2,
        SF: 2,
        E: 0,
        SB: 6,
        CS: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
  }

  getPitchersMockData(): PitcherStats[] {
    return [
      {
        playerId: 'PIT001',
        playerNumber: '15',
        playerName: '德保拉',
        IPOuts: 210,
        BF: 180,
        H: 145,
        HR: 12,
        BB: 35,
        IBB: 2,
        HB: 4,
        SO: 95,
        R: 60,
        ER: 52,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'PIT002',
        playerNumber: '18',
        playerName: '巴旺',
        IPOuts: 195,
        BF: 172,
        H: 138,
        HR: 10,
        BB: 32,
        IBB: 1,
        HB: 3,
        SO: 88,
        R: 55,
        ER: 48,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        playerId: 'PIT003',
        playerNumber: '21',
        playerName: '王溢正',
        IPOuts: 225,
        BF: 195,
        H: 152,
        HR: 14,
        BB: 38,
        IBB: 3,
        HB: 5,
        SO: 105,
        R: 68,
        ER: 60,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
  }

  getGameRecordsMockData(): GameRecord[] {
    return [
      {
        id: '1',
        pitcherName: '德保拉',
        batterName: '陳晨威',
        gameDate: new Date('2026-03-18'),
        inning: 1,
        result: '1B',
        isHit: true,
        isAB: true,
        bases: 1,
        rbi: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        pitcherName: '德保拉',
        batterName: '林家翔',
        gameDate: new Date('2026-03-18'),
        inning: 1,
        result: 'SO',
        isHit: false,
        isAB: true,
        bases: 0,
        rbi: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '3',
        pitcherName: '德保拉',
        batterName: '王柏融',
        gameDate: new Date('2026-03-18'),
        inning: 2,
        result: 'HR',
        isHit: true,
        isAB: true,
        bases: 4,
        rbi: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
  }
}
